[build]
  command = "npm run prebuild:netlify && npm run build"
  publish = "../passeios-ilhas/.next"

[build.environment]
  NODE_VERSION = "20.10.0"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/sucesso"
  to = "/sucesso"
  status = 200
